#!/bin/sh

echo 'for terminal colorscheme: import "One Dark.terminal" in MacOS Terminal'

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Linking dotfiles from ${BASEDIR}"

# link
ln -s ${BASEDIR}/gitconfig ~/.gitconfig
ln -s ${BASEDIR}/vimrc ~/.vimrc
ln -s ${BASEDIR}/zshrc ~/.zshrc
