#!/bin/bash

# view man pages with vim
export MANPAGER="col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -"

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [ -f $(brew --prefix)/etc/jump-module.bash ]; then
  . $(brew --prefix)/etc/jump-module.bash
fi
