TOOLS=~/.tools

ZSH=$TOOLS/zsh
source $ZSH/zplug.zsh
source $ZSH/aliases.zsh
source $ZSH/history.zsh
source $ZSH/keybindings.zsh
source $ZSH/prompt.zsh

export PATH=~/.bin:$PATH

source $TOOLS/brew/zsh
source $TOOLS/java/zsh
source $TOOLS/python/zsh
source $TOOLS/vscode/zsh
source $TOOLS/firefox.zsh
source $TOOLS/fzf.zsh
source $TOOLS/gcloud.zsh
source $TOOLS/gh.zsh
source $TOOLS/gradle.zsh
source $TOOLS/man.zsh
source $TOOLS/node.zsh
source $TOOLS/yarn.zsh