#!/usr/bin/env zsh

# pyenv
#######

# https://github.com/pyenv/pyenv#installation
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# poetry
########

export PATH="$HOME/.poetry/bin:$PATH"
# https://poetry.eustace.io/docs/#installation
alias poe="poetry run"