# Generated by ~/.gcloud/install.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/pedro/.gcloud/path.zsh.inc' ]; then . '/Users/pedro/.gcloud/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/pedro/.gcloud/completion.zsh.inc' ]; then . '/Users/pedro/.gcloud/completion.zsh.inc'; fi
