# Adapted from script generated by ~/.google-cloud-sdk/install.sh
GCLOUD_SDK=$HOME/.google-cloud-sdk

# The next line updates PATH for the Google Cloud SDK.
if [ -f $GCLOUD_SDK/path.zsh.inc ];
    then source $GCLOUD_SDK/path.zsh.inc;
fi

# The next line enables shell command completion for gcloud.
if [ -f $GCLOUD_SDK/completion.zsh.inc ];
    then source $GCLOUD_SDK/completion.zsh.inc;
fi
